const express = require('express');
const { Telegraf } = require('telegraf');
const { initializeApp, getApps } = require('firebase/app');
const { getFirestore, doc, getDoc, setDoc, collection, getDocs, query, orderBy, increment, updateDoc, deleteDoc } = require('firebase/firestore');

const BOT_TOKEN = process.env.BOT_TOKEN;
const WEBAPP_URL = process.env.WEBAPP_URL || "https://galeria-verifiedmodels.pages.dev";
const ADMIN_IDS_ENV = (process.env.ADMIN_IDS || "").split(",").map(s=>s.trim()).filter(Boolean);

if (!getApps().length) {
  initializeApp({ apiKey:"AIzaSyAIHevrpglvhHK3IsxpnkHlWpxnuf5o1So",authDomain:"galeria-verifiedmodels.firebaseapp.com",projectId:"galeria-verifiedmodels",storageBucket:"galeria-verifiedmodels.firebasestorage.app",messagingSenderId:"684551560793",appId:"1:684551560793:web:3730a07d8d6ec737e3db48"});
}
const db=getFirestore();
const bot = new Telegraf(BOT_TOKEN);

async function getConfig(){ try{ let s=await getDoc(doc(db,"config","bot")); if(s.exists()) return s.data(); }catch(e){} return {}; }
async function isAdmin(ctx){ let id=String(ctx.from?.id||""); if(ADMIN_IDS_ENV.includes(id)) return true; try{ let c=await getConfig(); if(c.admins && c.admins.includes(id)) return true; }catch(e){} if(ADMIN_IDS_ENV.length===0) return true; return false; }
function getMencion(ctx){ let n=(ctx.from.first_name||"").replace(/</g,'').replace(/>/g,''); return n?`<a href="tg://user?id=${ctx.from.id}">${n}</a>`:""; }
function replaceVars(str,m={},ctx=null){ if(!str) return ""; let total=(m.votosMalo||0)+(m.votosBueno||0); let pBueno=total?Math.round((m.votosBueno||0)/total*100):0; let lista=m.servicios?.map(s=>`• ${s}`).join('\n')||'• -'; let mencion=ctx?getMencion(ctx):"{mencion}"; return str.replaceAll('{mencion}',mencion).replaceAll('{perfil}',m.perfil||'').replaceAll('{username}',m.username||'').replaceAll('{edad}',String(m.edad||'')).replaceAll('{nacionalidad}',m.nacionalidad||'').replaceAll('{servicios}',m.servicios?.join(' • ')||'-').replaceAll('{servicios_lista}',lista).replaceAll('{descripcion}',m.descripcion||'').replaceAll('{votos}',String(total)).replaceAll('{votosBueno}',String(m.votosBueno||0)).replaceAll('{votosMalo}',String(m.votosMalo||0)).replaceAll('{porcentajeBueno}',String(pBueno)).replaceAll('{id}',m.id||'').replaceAll('{canalFree}',m.canalFree||m.canal_free||'https://t.me/').replaceAll('{contacto}',m.contacto||`https://t.me/${m.username||''}`); }
function getMediaModelo(m){ let c=[m.foto_file_id,m.foto,m.foto_url,m.fotoUrl,m.fotos?.[0]]; for(let x of c){ if(typeof x==='string'&&x.length>10) return x.trim(); if(typeof x==='object'&&x?.file_id) return x.file_id; } return null; }
let esperando={}; let plantillaTemp={};
const TEXTO_PANEL=`👑 <b>𝗣𝗔𝗡𝗘𝗟 𝗗𝗘 𝗖𝗢𝗡𝗙𝗚. 𝗔𝗗𝗠𝗜𝗡</b> 👑\n\n👋 BIENVENID@ AL PANEL\n\n💖 Que deseas hacer`;

bot.start(async(ctx)=>{ try{ const uid=String(ctx.from.id); try{ await setDoc(doc(db,"usuarios",uid),{id:uid,first_name:ctx.from.first_name||"",username:ctx.from.username||""},{merge:true}); }catch(e){} let c=await getConfig(); let texto=replaceVars(c.bienvenida_texto||"Hola {mencion} 👑",{},ctx); let kb=[[{text:"💖 𝗩𝗘𝗥 𝗚𝗔𝗟𝗘𝗥𝗜𝗔 𝗩𝗜𝗥𝗧𝗨𝗔𝗟 💖",web_app:{url:WEBAPP_URL},style:"success"}],[{text:"👑 𝗩𝗘𝗥 𝗟𝗜𝗦𝗧𝗔 𝗗𝗘 𝗠𝗢𝗗𝗘𝗟𝗢𝗦 👑",callback_data:"lista",style:"primary"}]]; let media=c.bienvenida_media||c.bienvenida_media_file_id; if(media){ try{ await ctx.replyWithPhoto(media,{caption:texto,parse_mode:'HTML',reply_markup:{inline_keyboard:kb}}); return; }catch(e){} } await ctx.reply(texto,{parse_mode:'HTML',reply_markup:{inline_keyboard:kb}}); }catch(e){ console.log(e); } });
bot.command('admin',async(ctx)=>{ if(!(await isAdmin(ctx))) return ctx.reply("❌ No eres admin"); delete esperando[String(ctx.from.id)]; await ctx.reply(TEXTO_PANEL,{parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:"👋 BIENVENIDA",callback_data:"panel_bienvenida",style:"primary"},{text:"💾 PLANTILLAS",callback_data:"panel_plantillas",style:"primary"}],[{text:"🖼️ GALERIA",callback_data:"panel_galeria",style:"success"},{text:"💃 MODELOS",callback_data:"panel_modelos",style:"success"}],[{text:"👥 USUARIOS",callback_data:"panel_usuarios",style:"danger"},{text:"👑 ADMINS",callback_data:"panel_admins",style:"danger"}]]}}); });
bot.command('cancel',async(ctx)=>{ delete esperando[String(ctx.from.id)]; await ctx.reply("✅ Cancelado - /admin"); });

bot.action('panel_bienvenida',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); await ctx.reply(`👋 <b>BIENVENIDA EDITOR</b>\nFoto: ${c.bienvenida_media?'✅':'❌'}\nTexto: ${(c.bienvenida_texto||'').substring(0,350)}\n\nVariables: {mencion}`,{parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:"📸 Cambiar FOTO",callback_data:"edit_bienvenida_foto",style:"primary"},{text:"📝 Cambiar TEXTO",callback_data:"edit_bienvenida_texto",style:"primary"}],[{text:"👁️ Preview",callback_data:"preview_start",style:"success"}],[{text:"⬅️ Volver",callback_data:"back_admin",style:"danger"}]]}}); });
bot.action('panel_galeria',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); await ctx.reply(`🖼️ <b>GALERIA EDITOR</b>\nFoto: ${c.galeria_media?'✅':'❌'}\nTexto: ${(c.galeria_texto||'').substring(0,350)}`,{parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:"📸 Foto",callback_data:"edit_galeria_foto",style:"primary"},{text:"📝 Texto",callback_data:"edit_galeria_texto",style:"primary"}],[{text:"⬅️ Volver",callback_data:"back_admin",style:"danger"}]]}}); });
bot.action('panel_plantillas',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); let snap=await getDocs(collection(db,"plantillas")).catch(()=>({docs:[]})); let kb=[]; snap.docs.slice(0,10).forEach(d=>{ kb.push([{text:`📄 ${d.data().nombre}`,callback_data:`plantilla_use_${d.id}`,style:"primary"},{text:"🗑️",callback_data:`plantilla_del_${d.id}`,style:"danger"}]); }); kb.push([{text:"➕ CREAR NUEVA",callback_data:"edit_plantilla_texto",style:"success"}]); kb.push([{text:"⬅️ Volver",callback_data:"back_admin",style:"danger"}]); await ctx.reply(`💾 <b>PLANTILLAS</b>\nActiva: ${(c.plantilla_texto||'').substring(0,500)}`,{parse_mode:'HTML',reply_markup:{inline_keyboard:kb}}); });
bot.action('panel_modelos',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let snap; try{ snap=await getDocs(query(collection(db,"modelos"),orderBy("fecha","desc"))); }catch{ snap=await getDocs(collection(db,"modelos")); } let kb=[]; let row=[]; snap.forEach(d=>{ let m=d.data(); let has=getMediaModelo(m)?"📸":"❌"; row.push({text:`${has} ${m.perfil||d.id}`,callback_data:`mfoto_${d.id}`,style:has==="📸"?"success":"danger"}); if(row.length===2){ kb.push(row); row=[]; } }); if(row.length) kb.push(row); kb.push([{text:"⬅️ Volver",callback_data:"back_admin",style:"danger"}]); await ctx.reply(`💃 MODELOS (${snap.size}) - toca para cambiar foto`,{reply_markup:{inline_keyboard:kb}}); });
bot.action('panel_usuarios',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let snap=await getDocs(collection(db,"usuarios")).catch(()=>({docs:[]})); let kb=[]; snap.docs.slice(0,15).forEach(d=>{ let u=d.data(); let banned=u.banned?"🚫":"✅"; kb.push([{text:`${banned} ${u.first_name||'Sin'} | ${d.id}`,callback_data:`user_ver_${d.id}`,style:u.banned?"danger":"success"},{text:u.banned?"✅ Unban":"🚫 Ban",callback_data:u.banned?`user_unban_${d.id}`:`user_ban_${d.id}`,style:u.banned?"success":"danger"}]); }); kb.push([{text:"⬅️ Volver",callback_data:"back_admin",style:"primary"}]); await ctx.reply(`👥 USUARIOS (${snap.size})`,{reply_markup:{inline_keyboard:kb}}); });
bot.action('panel_admins',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); let admins=c.admins||[]; let kb=[]; admins.forEach(id=>{ kb.push([{text:`👑 ${id}`,callback_data:`admin_ver_${id}`,style:"primary"},{text:"🗑️ Quitar",callback_data:`admin_del_${id}`,style:"danger"}]); }); kb.push([{text:"➕ Agregar Admin",callback_data:"admin_add",style:"success"}]); kb.push([{text:"⬅️ Volver",callback_data:"back_admin",style:"danger"}]); await ctx.reply(`👑 ADMINS (${admins.length})`,{reply_markup:{inline_keyboard:kb}}); });

bot.action('edit_bienvenida_foto',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='foto_bienvenida'; await ctx.reply("📸 Manda FOTO de bienvenida AHORA"); });
bot.action('edit_bienvenida_texto',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='texto_bienvenida'; await ctx.reply("📝 Manda TEXTO bienvenida con {mencion}"); });
bot.action('edit_galeria_foto',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='foto_galeria'; await ctx.reply("📸 Manda FOTO galeria"); });
bot.action('edit_galeria_texto',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='texto_galeria'; await ctx.reply("📝 Manda TEXTO galeria"); });
bot.action('edit_plantilla_texto',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='texto_plantilla'; await ctx.reply("📝 Manda PLANTILLA"); });
bot.action('admin_add',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='add_admin_id'; await ctx.reply("👑 Manda ID nuevo admin"); });
bot.action(/mfoto_(.*)/,async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); if(!(await isAdmin(ctx))) return; let id=ctx.match[1]; esperando[String(ctx.from.id)]=`foto_modelo_${id}`; await ctx.reply(`📸 Manda foto para ${id} ahora`); });
bot.action(/plantilla_use_(.*)/,async(ctx)=>{ if(!(await isAdmin(ctx))) return; let s=await getDoc(doc(db,"plantillas",ctx.match[1])); if(!s.exists()) return ctx.answerCbQuery("No existe"); await setDoc(doc(db,"config","bot"),{plantilla_texto:s.data().texto},{merge:true}); await ctx.answerCbQuery("✅ Activada"); });
bot.action(/plantilla_del_(.*)/,async(ctx)=>{ if(!(await isAdmin(ctx))) return; await deleteDoc(doc(db,"plantillas",ctx.match[1])); await ctx.answerCbQuery("Eliminada"); });
bot.action(/user_ban_(.*)/,async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); if(!(await isAdmin(ctx))) return; let id=ctx.match[1]; await setDoc(doc(db,"usuarios",String(id)),{banned:true},{merge:true}); await ctx.reply(`🚫 Baneado ${id}`); });
bot.action(/user_unban_(.*)/,async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); if(!(await isAdmin(ctx))) return; let id=ctx.match[1]; await setDoc(doc(db,"usuarios",String(id)),{banned:false},{merge:true}); await ctx.reply(`✅ Desbaneado ${id}`); });
bot.action(/admin_del_(.*)/,async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); if(!(await isAdmin(ctx))) return; let id=ctx.match[1]; let c=await getConfig(); let admins=(c.admins||[]).filter(a=>a!==String(id)); await setDoc(doc(db,"config","bot"),{admins},{merge:true}); await ctx.reply(`🗑️ Admin ${id} eliminado`); });
bot.action('back_admin',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); try{ await ctx.deleteMessage(); }catch(e){} await bot.telegram.sendMessage(ctx.from.id,TEXTO_PANEL,{parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:"👋 BIENVENIDA",callback_data:"panel_bienvenida",style:"primary"},{text:"💾 PLANTILLAS",callback_data:"panel_plantillas",style:"primary"}],[{text:"🖼️ GALERIA",callback_data:"panel_galeria",style:"success"},{text:"💃 MODELOS",callback_data:"panel_modelos",style:"success"}],[{text:"👥 USUARIOS",callback_data:"panel_usuarios",style:"danger"},{text:"👑 ADMINS",callback_data:"panel_admins",style:"danger"}]]}}); });
bot.action('preview_start',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); let texto=replaceVars(c.bienvenida_texto||"Hola {mencion}",{},ctx); let media=c.bienvenida_media; if(media){ try{ await ctx.replyWithPhoto(media,{caption:texto,parse_mode:'HTML'}); return; }catch(e){} } await ctx.reply(texto,{parse_mode:'HTML'}); });

bot.on('photo',async(ctx)=>{ if(!(await isAdmin(ctx))) return; let key=String(ctx.from.id); let st=esperando[key]; if(!st) return; let fileId=ctx.message.photo[ctx.message.photo.length-1].file_id; if(st.startsWith('foto_modelo_')){ let id=st.replace('foto_modelo_',''); await setDoc(doc(db,"modelos",id),{foto_file_id:fileId,foto:fileId},{merge:true}); delete esperando[key]; return ctx.reply(`✅ Foto modelo ${id} guardada`); } if(st==='foto_bienvenida'){ await setDoc(doc(db,"config","bot"),{bienvenida_media:fileId,bienvenida_media_file_id:fileId},{merge:true}); delete esperando[key]; return ctx.reply("✅ BIENVENIDA foto guardada"); } if(st==='foto_galeria'){ await setDoc(doc(db,"config","bot"),{galeria_media:fileId,galeria_media_file_id:fileId},{merge:true}); delete esperando[key]; return ctx.reply("✅ GALERIA foto guardada"); } });
bot.on('text',async(ctx)=>{ let txt=ctx.message.text; if(txt.startsWith('/')) return; if(!(await isAdmin(ctx))) return; let key=String(ctx.from.id); let st=esperando[key]; if(!st) return; if(st==='texto_bienvenida'){ await setDoc(doc(db,"config","bot"),{bienvenida_texto:txt},{merge:true}); delete esperando[key]; return ctx.reply("✅ BIENVENIDA texto guardado"); } if(st==='texto_galeria'){ await setDoc(doc(db,"config","bot"),{galeria_texto:txt},{merge:true}); delete esperando[key]; return ctx.reply("✅ GALERIA texto guardado"); } if(st==='texto_plantilla'){ plantillaTemp[key]={texto:txt}; esperando[key]='nombre_plantilla'; return ctx.reply("Ahora manda NOMBRE de plantilla"); } if(st==='nombre_plantilla'){ let temp=plantillaTemp[key]; let nombre=txt.slice(0,40); let newId=Date.now().toString(); await setDoc(doc(db,"plantillas",newId),{nombre,texto:temp.texto,fecha:new Date().toISOString()}); await setDoc(doc(db,"config","bot"),{plantilla_texto:temp.texto},{merge:true}); delete esperando[key]; delete plantillaTemp[key]; return ctx.reply(`✅ Plantilla "${nombre}" creada`); } if(st==='add_admin_id'){ let id=txt.replace(/\D/g,''); if(!id) return ctx.reply("ID invalido"); let c=await getConfig(); let admins=c.admins||[]; if(!admins.includes(id)) admins.push(id); await setDoc(doc(db,"config","bot"),{admins},{merge:true}); delete esperando[key]; return ctx.reply(`👑 Admin ${id} agregado`); } });

bot.action('lista',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); let texto=replaceVars(c.galeria_texto||"👑 GALERIA {mencion}",{},ctx); let snap; try{ snap=await getDocs(query(collection(db,"modelos"),orderBy("fecha","desc"))); }catch{ snap=await getDocs(collection(db,"modelos")); } let kb=[]; let row=[]; snap.forEach(d=>{ let m=d.data(); let btn={text:(m.perfil||d.id).replace(/@/g,'').trim(),callback_data:`ver_${d.id}`,style:row.length===0?"primary":"danger"}; row.push(btn); if(row.length===2){ kb.push(row); row=[]; } }); if(row.length) kb.push(row); kb.push([{text:"𝗩𝗘𝗥 𝗚𝗔𝗟𝗘𝗥𝗜𝗔 𝗩𝗜𝗥𝗧𝗨𝗔𝗟 💖",web_app:{url:WEBAPP_URL},style:"success"}]); let media=c.galeria_media||c.galeria_media_file_id; try{ await ctx.deleteMessage(); }catch(e){} if(media){ try{ await ctx.replyWithPhoto(media,{caption:texto,parse_mode:'HTML',reply_markup:{inline_keyboard:kb}}); return; }catch(e){} } await ctx.reply(texto,{parse_mode:'HTML',reply_markup:{inline_keyboard:kb}}); });

bot.action(/ver_(.*)/,async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let id=ctx.match[1].trim(); let snap=await getDoc(doc(db,"modelos",id)); if(!snap.exists()) return ctx.reply("❌ No existe"); let m={id:snap.id,...snap.data()}; let c=await getConfig(); let caption=replaceVars(c.plantilla_texto||"👑 {perfil} 👑\nHola {mencion}\nVotos: {votos}\n{servicios_lista}",m,ctx); let media=getMediaModelo(m); let canalFree=m.canalFree||"https://t.me/"; let contacto=m.contacto||`https://t.me/${m.username||''}`; let kb=[[{text:"💖 𝗩𝗘𝗥 𝗣𝗘𝗥𝗙𝗜𝗟 𝗖𝗢𝗠𝗣𝗟𝗘𝗧𝗢 💖",web_app:{url:`${WEBAPP_URL}?m=${m.id}`},style:"success"}],[{text:`👍 Bueno ${m.votosBueno||0}`,callback_data:`voto_bueno_${m.id}`,style:"success"},{text:`👎 Malo ${m.votosMalo||0}`,callback_data:`voto_malo_${m.id}`,style:"danger"}],[{text:"💎 𝗖𝗔𝗡𝗔𝗟 𝗙𝗥𝗘𝗘",url:canalFree,style:"primary"},{text:"💬 𝗖𝗢𝗡𝗧𝗔𝗖𝗧𝗔𝗥",url:contacto,style:"primary"}],[{text:"👈🏻 VOLVER",callback_data:"lista",style:"danger"},{text:"👑 INICIO",callback_data:"inicio",style:"danger"}]]; try{ await ctx.deleteMessage(); }catch(e){} if(media){ try{ await ctx.replyWithPhoto(media,{caption,parse_mode:'HTML',reply_markup:{inline_keyboard:kb}}); return; }catch(e){} } await ctx.reply(caption,{parse_mode:'HTML',reply_markup:{inline_keyboard:kb}}); });

bot.action('inicio',async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); let texto=replaceVars(c.bienvenida_texto||"Hola {mencion} 👑",{},ctx); let kb=[[{text:"💖 GALERÍA",web_app:{url:WEBAPP_URL},style:"success"}],[{text:"📋 LISTA",callback_data:"lista",style:"primary"}]]; let media=c.bienvenida_media; try{ await ctx.deleteMessage(); }catch(e){} if(media){ try{ await ctx.replyWithPhoto(media,{caption:texto,parse_mode:'HTML',reply_markup:{inline_keyboard:kb}}); return; }catch(e){} } await ctx.reply(texto,{parse_mode:'HTML',reply_markup:{inline_keyboard:kb}}); });

bot.action(/voto_(bueno|malo)_(.*)/,async(ctx)=>{ await ctx.answerCbQuery("✅").catch(()=>{}); let tipo=ctx.match[1]; let id=ctx.match[2]; let ref=doc(db,"modelos",id); if(tipo==='bueno') await updateDoc(ref,{votosBueno:increment(1)}).catch(async()=>{ await setDoc(ref,{votosBueno:1},{merge:true}); }); else await updateDoc(ref,{votosMalo:increment(1)}).catch(async()=>{ await setDoc(ref,{votosMalo:1},{merge:true}); }); });

const app=express(); app.use(express.json());
app.get('/',(req,res)=>res.send('Bot OK en Render 24/7 - Colores ON'));
app.post('/webhook',(req,res)=>{ bot.handleUpdate(req.body).then(()=>res.send('ok')).catch(()=>res.send('ok')); });
const PORT=process.env.PORT||3000;
app.listen(PORT,async()=>{ console.log('Bot iniciado puerto '+PORT); const external=process.env.RENDER_EXTERNAL_URL; if(external){ try{ await bot.telegram.setWebhook(`${external}/webhook`); console.log('Webhook set:',`${external}/webhook`); }catch(e){ console.log('Webhook error',e.message); } } });
