const { bot } = require('../bot');
const { getConfig, getModelos, clearCache } = require('../cache');
const { isAdmin } = require('../utils');
const { doc, getDoc, setDoc, collection, getDocs, deleteDoc } = require('firebase/firestore');
const { db } = require('../firebase');
let esperando={}; let temp={};
module.exports.esperando=esperando;
module.exports.temp=temp;
const PANEL_TEXTO=`👑 <b>PANEL ADMIN V14 MODULAR</b> 👑`;

bot.command('admin', async(ctx)=>{
  if(!(await isAdmin(ctx))) return; delete esperando[String(ctx.from.id)];
  await ctx.reply(PANEL_TEXTO,{parse_mode:'HTML',reply_markup:{inline_keyboard:[
    [{text:"👋🏻 BIENVENIDA",callback_data:"panel_bienvenida", style:"danger"},{text:"📝 PLANTILLAS",callback_data:"panel_plantillas", style:"danger"}],
    [{text:"🖼️ GALERIA",callback_data:"panel_galeria", style:"primary"},{text:"👸🏻 MODELOS",callback_data:"panel_modelos", style:"primary"}],
    [{text:"👑 ADMINS",callback_data:"panel_admins", style:"success"},{text:"🧩 BOTONES",callback_data:"panel_botones", style:"success"}]
  ]}});
});
bot.command('cancel', async(ctx)=>{ delete esperando[String(ctx.from.id)]; await ctx.reply("✅"); });

bot.action('panel_bienvenida', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); await ctx.reply(`👋🏻 BIENVENIDA\nFoto: ${c.bienvenida_media?'✅':'❌'}`,{reply_markup:{inline_keyboard:[[{text:"📸 Foto",callback_data:"edit_bienvenida_foto", style:"primary"},{text:"📝 Texto Premium",callback_data:"edit_bienvenida_texto", style:"primary"}],[{text:"👁️ Preview",callback_data:"preview_start", style:"success"}],[{text:"⬅️ Volver",callback_data:"back_admin", style:"danger"}]]}}); });
bot.action('panel_galeria', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); await ctx.reply(`🖼️ GALERIA`,{reply_markup:{inline_keyboard:[[{text:"📸 Foto",callback_data:"edit_galeria_foto", style:"primary"},{text:"📝 Texto",callback_data:"edit_galeria_texto", style:"primary"}],[{text:"⬅️ Volver",callback_data:"back_admin", style:"danger"}]]}}); });
bot.action('panel_plantillas', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let snap=await getDocs(collection(db,"plantillas")).catch(()=>({docs:[]})); let kb=[]; snap.docs.slice(0,15).forEach(d=>{ kb.push([{text:`📄 ${d.data().nombre}`,callback_data:`plantilla_use_${d.id}`, style:"primary"},{text:"🗑️",callback_data:`plantilla_del_${d.id}`, style:"danger"}]); }); kb.push([{text:"➕ CREAR PREMIUM",callback_data:"edit_plantilla_texto", style:"success"}]); kb.push([{text:"⬅️ Volver",callback_data:"back_admin", style:"danger"}]); await ctx.reply("📝 PLANTILLAS",{reply_markup:{inline_keyboard:kb}}); });
bot.action('panel_modelos', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let snap=await getModelos(); let kb=[]; let row=[]; snap.forEach(d=>{ row.push({text:d.data().perfil||d.id,callback_data:`mfoto_${d.id}`, style:"primary"}); if(row.length===2){ kb.push(row); row=[]; } }); if(row.length) kb.push(row); kb.push([{text:"⬅️ Volver",callback_data:"back_admin", style:"danger"}]); await ctx.reply(`👸🏻 MODELOS (${snap.size})`,{reply_markup:{inline_keyboard:kb}}); });
bot.action('panel_admins', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); let kb=[]; (c.admins||[]).forEach(id=>{ kb.push([{text:`👑 ${id}`,callback_data:"noop", style:"primary"},{text:"🗑️",callback_data:`admin_del_${id}`, style:"danger"}]); }); kb.push([{text:"➕ Añadir Admin",callback_data:"admin_add", style:"success"}]); kb.push([{text:"⬅️ Volver",callback_data:"back_admin", style:"danger"}]); await ctx.reply("👑 ADMINS",{reply_markup:{inline_keyboard:kb}}); });
bot.action('panel_botones', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); await ctx.reply("🧩 BOTONES - Nombre, color, premium",{reply_markup:{inline_keyboard:[[{text:"BIENVENIDA",callback_data:"botones_bienvenida", style:"danger"}],[{text:"GALERIA",callback_data:"botones_galeria", style:"primary"}],[{text:"PLANTILLA",callback_data:"botones_plantilla", style:"success"}],[{text:"⬅️ Volver",callback_data:"back_admin", style:"danger"}]]}}); });

bot.action('botones_bienvenida', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); await ctx.reply("BIENVENIDA",{reply_markup:{inline_keyboard:[[{text:"VIRTUAL 🔵 WEDAPP",callback_data:"edit_btn_bienvenida_galeria_virtual", style:"primary"}],[{text:"LISTA 🔴",callback_data:"edit_btn_bienvenida_lista_modelos", style:"danger"}],[{text:"CANAL 🟢",callback_data:"edit_btn_bienvenida_canal_oficial", style:"success"}],[{text:"⬅️ Volver",callback_data:"panel_botones", style:"danger"}]]}}); });
bot.action('botones_galeria', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); await ctx.reply("GALERIA",{reply_markup:{inline_keyboard:[[{text:"🎨 Hileras 🔵🔴",callback_data:"edit_galeria_colores", style:"primary"}],[{text:"CANAL 🟢",callback_data:"edit_btn_galeria_canal", style:"success"}],[{text:"VIRTUAL 🔵",callback_data:"edit_btn_galeria_virtual", style:"primary"}],[{text:"⬅️ Volver",callback_data:"panel_botones", style:"danger"}]]}}); });
bot.action('botones_plantilla', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); await ctx.reply("PLANTILLA",{reply_markup:{inline_keyboard:[[{text:"PERFIL 🔵",callback_data:"edit_btn_plantilla_perfil", style:"primary"}],[{text:"BUENO 🟢",callback_data:"edit_btn_plantilla_bueno", style:"success"},{text:"MALO 🔴",callback_data:"edit_btn_plantilla_malo", style:"danger"}],[{text:"FREE 🔵",callback_data:"edit_btn_plantilla_free", style:"primary"},{text:"CONTACTAME 🔵",callback_data:"edit_btn_plantilla_contacto", style:"primary"}],[{text:"VOLVER 🔴",callback_data:"edit_btn_plantilla_volver", style:"danger"},{text:"INICIO 🔴",callback_data:"edit_btn_plantilla_inicio", style:"danger"}],[{text:"⬅️ Volver",callback_data:"panel_botones", style:"danger"}]]}}); });

bot.action(/edit_btn_(.*)/, async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]=`btn_${ctx.match[1]}`; await ctx.reply(`🧩 Manda nombre premium para ${ctx.match[1]}`); });
bot.action('edit_galeria_colores', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='galeria_colores'; await ctx.reply("Manda: 🔵 🔴"); });
bot.action('edit_bienvenida_foto', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='foto_bienvenida'; await ctx.reply("📸 Foto"); });
bot.action('edit_bienvenida_texto', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='texto_bienvenida'; await ctx.reply("📝 Texto bienvenida {mencion} premium"); });
bot.action('edit_galeria_foto', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='foto_galeria'; await ctx.reply("📸 Foto galeria"); });
bot.action('edit_galeria_texto', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='texto_galeria'; await ctx.reply("📝 Texto galeria"); });
bot.action('edit_plantilla_texto', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='texto_plantilla'; await ctx.reply("📝 Plantilla {perfil} @{username} {edad} {nacionalidad} {Lista_servicios} {descripcion} {Votos} {porcentaje_buenos}% {porcentaje_malos}%"); });
bot.action('admin_add', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]='add_admin_id'; await ctx.reply("ID admin"); });
bot.action(/mfoto_(.*)/, async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); esperando[String(ctx.from.id)]=`foto_modelo_${ctx.match[1]}`; await ctx.reply(`Foto para ${ctx.match[1]}`); });
bot.action(/plantilla_use_(.*)/, async(ctx)=>{ await ctx.answerCbQuery("✅").catch(()=>{}); let s=await getDoc(doc(db,"plantillas",ctx.match[1])); if(s.exists()){ await setDoc(doc(db,"config","bot"),{plantilla_texto:s.data().texto,plantilla_entities:s.data().entities||[]},{merge:true}); clearCache(); } });
bot.action(/plantilla_del_(.*)/, async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); await deleteDoc(doc(db,"plantillas",ctx.match[1])); });
bot.action(/admin_del_(.*)/, async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); let admins=(c.admins||[]).filter(a=>a!==ctx.match[1]); await setDoc(doc(db,"config","bot"),{admins},{merge:true}); clearCache(); await ctx.reply("Eliminado"); });
bot.action('back_admin', async(ctx)=>{ try{ await ctx.answerCbQuery().catch(()=>{}); await ctx.deleteMessage().catch(()=>{}); }catch(e){} await bot.telegram.sendMessage(ctx.from.id,`👑 <b>PANEL ADMIN V14</b> 👑`,{parse_mode:'HTML',reply_markup:{inline_keyboard:[[{text:"👋🏻 BIENVENIDA",callback_data:"panel_bienvenida", style:"danger"},{text:"📝 PLANTILLAS",callback_data:"panel_plantillas", style:"danger"}],[{text:"🖼️ GALERIA",callback_data:"panel_galeria", style:"primary"},{text:"👸🏻 MODELOS",callback_data:"panel_modelos", style:"primary"}],[{text:"👑 ADMINS",callback_data:"panel_admins", style:"success"},{text:"🧩 BOTONES",callback_data:"panel_botones", style:"success"}]]}}); });
bot.action('preview_start', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); let c=await getConfig(); let texto=require('../utils').replaceVars(c.bienvenida_texto||"Hola {mencion}",{},ctx); if(c.bienvenida_media){ try{ await ctx.replyWithPhoto(c.bienvenida_media,{caption:texto,parse_mode:'HTML'}); return; }catch(e){} } await ctx.reply(texto,{parse_mode:'HTML'}); });
bot.action('noop', async(ctx)=>{ await ctx.answerCbQuery().catch(()=>{}); });
